use_frameworks!

platform :ios, '8.0'

target 'DWCocoapods-bin_Example' do
  pod 'DWCocoapods-bin', :path => '../'

  target 'DWCocoapods-bin_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
